### PR TITLE
New feature allowing to show links to a wiki on alarms

### PR DESCRIPTION
**Pull request by piogor**
Solaris requested to provide links to Wiki pages on alarms.
It is done as a link appearing in alarm window widget, if there is `AlarmWikiLink` PyAlarm class property defined.
The link is formed from this property by substitution of `{%ALARM%}` with actual alarm name. So, the value of the property may looks like: `http://wiki.cps.uj.edu.pl/alarms/{%ALARM%}`.

### CODE REVIEW

**Comment by sergirubio** [comment]
Hi Piotr,

I'll have a look into that, actually the syntax is similar but a bit different from what is used for PhoneBook entries in receivers.

I'll try to have a common solution for both cases just to avoid having unconsistent markup in the properties.

Sergi

**Comment by sergirubio** [comment]
I'm doing some comments on the PR

https://github.com/tango-controls/PANIC/blob/documentation/doc/contribute.rst

**Comment by sergirubio** [comment]
I added an small file to the documentation:

https://github.com/tango-controls/PANIC/blob/documentation/doc/recipes/AlarmWikiLink.rst

**Comment by MikeFalowski** [comment]
I would ask only for changing the link example to: `http://wiki.example.com/alarms/{%ALARM%}` or any different.

**Comment by sergirubio** [comment]
Done!, thanks for the comment Mike

**Comment by MikeFalowski** [comment]
No problem and thanks for change!

**Pull request merged**
