### PR TITLE
Added PyQt5 support

### PR DESCRIPTION
**Pull request by kapot65**
- Added new syntax for signals and slots
- Changed obsolete Qt methods

### CODE REVIEW

**Comment by kapot65** [comment]
Hello!

I've added PyQt5 support to make this project work from docker container (Qt4 seems to be bugged - it shows blank widget instead of gui). On Qt4, the program should work just like it did. 

There are 2 things worth checking out:
1. AlarmForm.valueChanged -> AlarmForm.changeValue. I had to rename it since it duplicates signal name. Not sure it works properly now.
2. utils.get_archive_trend - TaurusTrend seems to use deprecated api. I dont know how to fix it.

I will be glad if you review and accept my changes.

**Comment by sergirubio** [comment]
Hi kapot65,

Thanks for the pull request. I'm going to test it and come back with feedback.

Sergi

**Comment by sergirubio** [comment]
hi, the project has been moved to gitlab and the work will continue there

https://gitlab.com/tango-controls/panic/-/issues?sort=created_date&state=opened

**Comment by sergirubio** [comment]
if you have a gitlab user, just make a comment on your issue and I'll try to link it back to you

**Pull request closed without merging**
